### PR TITLE
Expose WizardConstructor and add Wizard.extendOptions 

### PR DESCRIPTION
**Pull request by bySabi**
This PR add `Wizard.extendOptions` API and expose `WizardConstructor`to global.
I think is all is needed for customize wizard behaviour.
@Pagebakers review this PR.

### CODE REVIEW

**Comment by Pagebakers** [comment]
Great! I like the idea, let me get back to this asap.

**Comment by bySabi** [comment]
Good!! I extend `wizard`a little to couple `on place edit` behavior, like this  http://meteorpad.com/pad/uzCXLFqpSYjvSJkEa/Copy%20of%20AutoForm%20simple%20Edit but on wizard.
This is a WIP ...

But! for properly function AutoForm Schema reactivity bug must be fixed. I make a PR here: https://github.com/aldeed/meteor-autoform/pull/1205 , I don´t fix this. Only merge again and pull it ... 

I you have interest on, `on place edit` behavior just tell me and I'll post the code.
This is AutoForm branch with fixed Schema reactivity bug: https://github.com/bySabi/meteor-autoform

by the way , I enjoy reading your code. Well done!!

**Comment by bySabi** [comment]
@Pagebakers  this PR or https://github.com/forwarder/meteor-wizard/pull/41 must be revamped upon the merge order. Each one touch `WizardConstructor` .

**Comment by Pagebakers** [comment]
This has been merged with #43

**Pull request closed without merging**
