### PR TITLE
expose WizardRouter

### PR DESCRIPTION
**Pull request by bySabi**
@Pagebakers review this PR please.
In order to customize router behaviour `WizardRouter` must be expose.

by the way I rewrite meteor-wizard-example using FlowRouter and Bootstrap. Is here: https://github.com/bySabi/meteor-wizard-example-with-flowrouter-bootstrap . Review too and copy paste on `meteor-wizard` project.

### CODE REVIEW

**Comment by Pagebakers** [comment]
What behaviour would be need to change?

Many thanks for the example! Can you deploy this to meteor, so there's a running example too? then I'll add the links to the readme.

**Comment by bySabi** [comment]
I need create my own registerHelper `pathForStep` and for this `WizardRouter` must be expose.

I have to fix a minor bug on `nav-wizard` less file before deploy to meteor. I´ll be in touch with this.

Add too a `reload` method to router.js. FlowRouter don´t rerender the same step if you use FlowRouter.go. Now my custom show method is ... 

```
  show: function(id) {
    if(typeof id === 'number') {
      id = id in this._stepsByIndex && this._stepsByIndex[id];
    }

    if(!id) return false;

    if(this.route) {
      if (id === this._activeStepId) {
        WizardRouter.reload(this.route, id);
      } else {
        WizardRouter.go(this.route, id);
      }
    } else {
      this.setStep(id);
    }

    return true;
  }
```

**Comment by bySabi** [comment]
@Pagebakers  I deploy FlowRouter  Bootstrap example. http://autoform-wizard-flowrouter-bootstrap.meteor.com

**Comment by bySabi** [comment]
See we don´t need router reload method, only fired reactivity on show method. This way:
```
  show: function(id) {
    if(typeof id === 'number') {
      id = id in this._stepsByIndex && this._stepsByIndex[id];
    }

    if(!id) return false;

    if (this.isActiveStep(id)) this._dep.changed();

    if(this.route) {
      WizardRouter.go(this.route, id);
    } else {
      this.setStep(id);
    }

    return true;
  }
```

What you think @Pagebakers ? 
is this correct I'll remove current PR and  https://github.com/forwarder/autoform-wizard-flow-router/pull/4

**Comment by Pagebakers** [comment]
I see, it's intended to work this way, if the step is the same, it shoudn't re-render again. Why do you need it to rerender?

**Comment by bySabi** [comment]
I rerender when switch the form type from 'readonly' to 'method-update' and viceversa.
This PR is not needed cause I create a custom method who call `this._dep.changed()`
But still need WizardRouter gobal.

**Comment by Pagebakers** [comment]
You can achieve that without changing the wizard internals right? You can make the type a reactive variable

**Comment by bySabi** [comment]
Thats correct!. Initially I thought a internal wizard change is needed but lately I realize that can doit with a reactive var. Because it I close this PR

**Comment by Pagebakers** [comment]
Awesome!

**Pull request closed without merging**
